name: moodsense_client_example
description: Example Dart client for MoodSense API
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0
  cryptography: ^2.5.0
